import localFont from "next/font/local";
import "./globals.css";
import bannerImg from "../public/medicare.jpg";
import "react-toastify/dist/ReactToastify.css";
import Image from "next/image";
import { ToastContainer } from "react-toastify";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Mr Doctor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative h-[300px] sm:h-[400px] lg:h-screen">
          <Image src={bannerImg} layout="fill" alt="banner" objectFit="cover" />
          {/* Full White Gradient Overlay */}
          <div className="absolute top-0 left-0 inset-0 bg-gradient-to-t from-white via-white to-white opacity-80" />
          {children}
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
